=== Open-Inflation/fixprice_api/tests/__snapshots__/unstandard_urls.schema.json
{
  "type": "object",
  "required": [
    "https://api.fix-price.com/buyer/v1/banner/suitable?type=1&path=https:%2F%2Ffix-price.com%2Fcatalog",
    "https://api.fix-price.com/buyer/v1/config/ecom.product.special.price.date.show",
    "https://api.fix-price.com/buyer/v1/cookie-config",
    "https://api.fix-price.com/buyer/v2/geo/ip",
    "https://api.fix-price.com/buyer/v2/geo/ip?utm_referrer=https%3a%2f%2ffix-price.com%2f"
  ],
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "properties": {
    "https://api.fix-price.com/buyer/v1/banner/suitable?type=1&path=https:%2F%2Ffix-price.com%2Fcatalog": {
      "$ref": "#/$defs/Object1"
    },
    "https://api.fix-price.com/buyer/v1/banner/suitable?type=1&path=https:%2F%2Ffix-price.com%2Fcatalog&utm_referrer=https%3a%2f%2ffix-price.com%2f": {
      "$ref": "#/$defs/Object1"
    },
    "https://api.fix-price.com/buyer/v1/category/menu": {
      "$ref": "#/$defs/Object1"
    },
    "https://api.fix-price.com/buyer/v1/category/menu?utm_referrer=https%3a%2f%2ffix-price.com%2f": {
      "$ref": "#/$defs/Object1"
    },
    "https://api.fix-price.com/buyer/v1/config/ecom.product.special.price.date.show": {
      "$ref": "#/$defs/Object1"
    },
    "https://api.fix-price.com/buyer/v1/config/ecom.product.special.price.date.show?utm_referrer=https%3a%2f%2ffix-price.com%2f": {
      "$ref": "#/$defs/Object1"
    },
    "https://api.fix-price.com/buyer/v1/cookie-config": {
      "$ref": "#/$defs/Object1"
    },
    "https://api.fix-price.com/buyer/v2/geo/ip": {
      "$ref": "#/$defs/Object1"
    },
    "https://api.fix-price.com/buyer/v2/geo/ip?utm_referrer=https%3a%2f%2ffix-price.com%2f": {
      "$ref": "#/$defs/Object1"
    },
    "https://fix-price.com/api/sigma/experiment/feature?experiment=cartprod_he5RUJQS&param=cart_prod": {
      "$ref": "#/$defs/Object2"
    },
    "https://fix-price.com/api/sigma/experiment/feature?experiment=chatbot_RAJUTXCv&param=chat_bot": {
      "$ref": "#/$defs/Object2"
    },
    "https://fix-price.com/api/sigma/experiments": {
      "$ref": "#/$defs/Object2"
    },
    "https://fix-price.com/img/Header/card.svg": {
      "type": "object",
      "required": [
        "traceparent"
      ],
      "properties": {
        "traceparent": {
          "type": "array",
          "items": {
            "type": "string",
            "j2sEnumRejected": true
          }
        }
      }
    },
    "https://fix-price.com/img/Header/icons/search.svg": {
      "type": "object",
      "required": [
        "traceparent"
      ],
      "properties": {
        "traceparent": {
          "type": "array",
          "items": {
            "type": "string",
            "j2sEnumRejected": true
          }
        }
      }
    },
    "https://fix-price.com/img/Header/logo.svg": {
      "type": "object",
      "required": [
        "traceparent"
      ],
      "properties": {
        "traceparent": {
          "type": "array",
          "items": {
            "type": "string",
            "j2sEnumRejected": true
          }
        }
      }
    },
    "https://fix-price.com/img/common/cart.svg": {
      "type": "object",
      "required": [
        "traceparent"
      ],
      "properties": {
        "traceparent": {
          "type": "array",
          "items": {
            "type": "string",
            "j2sEnumRejected": true
          }
        }
      }
    },
    "https://fix-price.com/img/common/chevron.svg": {
      "type": "object",
      "required": [
        "traceparent"
      ],
      "properties": {
        "traceparent": {
          "type": "array",
          "items": {
            "type": "string",
            "j2sEnumRejected": true
          }
        }
      }
    },
    "https://fix-price.com/img/common/logout.svg": {
      "type": "object",
      "required": [
        "traceparent"
      ],
      "properties": {
        "traceparent": {
          "type": "array",
          "items": {
            "type": "string",
            "j2sEnumRejected": true
          }
        }
      }
    },
    "https://rm.fix-price.com/intake/v2/rum/events": {
      "type": "object",
      "required": [
        "content-encoding"
      ],
      "properties": {
        "content-encoding": {
          "type": "array",
          "items": {
            "type": "string",
            "enum": [
              "gzip"
            ]
          }
        }
      }
    }
  },
  "$defs": {
    "Object1": {
      "type": "object",
      "required": [
        "x-city",
        "x-client-route",
        "x-key",
        "x-language",
        "x-logged"
      ],
      "minProperties": 1,
      "properties": {
        "x-city": {
          "type": "array",
          "minItems": 1,
          "items": {
            "type": "string",
            "j2sEnumRejected": true
          }
        },
        "x-client-route": {
          "type": "array",
          "minItems": 1,
          "items": {
            "type": "string",
            "enum": [
              "/catalog"
            ]
          }
        },
        "x-key": {
          "type": "array",
          "minItems": 1,
          "items": {
            "type": "string",
            "j2sEnumRejected": true
          }
        },
        "x-language": {
          "type": "array",
          "minItems": 1,
          "items": {
            "type": "string",
            "enum": [
              "ru"
            ]
          }
        },
        "x-logged": {
          "type": "array",
          "minItems": 1,
          "items": {
            "type": "string",
            "j2sEnumRejected": true
          }
        }
      }
    },
    "Object2": {
      "type": "object",
      "required": [
        "x-sigma-ip",
        "x-sigma-platform",
        "x-sigma-ua",
        "x-sigma-user-id"
      ],
      "minProperties": 1,
      "properties": {
        "traceparent": {
          "type": "array",
          "minItems": 1,
          "items": {
            "type": "string",
            "j2sEnumRejected": true
          }
        },
        "x-sigma-ip": {
          "type": "array",
          "minItems": 1,
          "items": {
            "type": "string",
            "j2sEnumRejected": true
          }
        },
        "x-sigma-platform": {
          "type": "array",
          "minItems": 1,
          "items": {
            "type": "string",
            "enum": [
              "web"
            ]
          }
        },
        "x-sigma-ua": {
          "type": "array",
          "minItems": 1,
          "items": {
            "type": "string",
            "j2sEnumRejected": true
          }
        },
        "x-sigma-user-id": {
          "type": "array",
          "minItems": 1,
          "items": {
            "type": "string",
            "j2sEnumRejected": true
          }
        }
      }
    }
  }
}

=== Open-Inflation/fixprice_api/tests/__snapshots__/unstandard_urls.json
{
  "https://api.fix-price.com/buyer/v1/config/ecom.product.special.price.date.show": {
    "x-language": [
      "ru"
    ],
    "x-city": [
      "3"
    ],
    "x-key": [
      "UnY0S1pOK09NY0sraTNyYUlRaFJZdz09OjpBVkRLZlVMcWF1aS8wZEppZVlTUjdBPT0=:877694bb30bad8cdaf6a905f6bb6055e"
    ],
    "x-logged": [
      ""
    ],
    "x-client-route": [
      "/catalog"
    ]
  },
  "https://api.fix-price.com/buyer/v1/config/ecom.product.special.price.date.show?utm_referrer=https%3a%2f%2ffix-price.com%2f": {
    "x-language": [
      "ru"
    ],
    "x-city": [
      "3"
    ],
    "x-key": [
      "UnY0S1pOK09NY0sraTNyYUlRaFJZdz09OjpBVkRLZlVMcWF1aS8wZEppZVlTUjdBPT0=:877694bb30bad8cdaf6a905f6bb6055e"
    ],
    "x-logged": [
      ""
    ],
    "x-client-route": [
      "/catalog"
    ]
  },
  "https://fix-price.com/api/sigma/experiments": {
    "x-sigma-user-id": [
      "UnY0S1pOK09NY0sraTNyYUlRaFJZdz09OjpBVkRLZlVMcWF1aS8wZEppZVlTUjdBPT0=:877694bb30bad8cdaf6a905f6bb6055e"
    ],
    "x-sigma-platform": [
      "web"
    ],
    "x-sigma-ua": [
      ""
    ],
    "x-sigma-ip": [
      ""
    ],
    "traceparent": [
      "00-a91ec628c02c6fa18efb75e048492dd3-a9a5a350baaac605-00"
    ]
  },
  "https://fix-price.com/api/sigma/experiment/feature?experiment=cartprod_he5RUJQS&param=cart_prod": {
    "x-sigma-user-id": [
      "UnY0S1pOK09NY0sraTNyYUlRaFJZdz09OjpBVkRLZlVMcWF1aS8wZEppZVlTUjdBPT0=:877694bb30bad8cdaf6a905f6bb6055e"
    ],
    "x-sigma-platform": [
      "web"
    ],
    "x-sigma-ua": [
      ""
    ],
    "x-sigma-ip": [
      ""
    ]
  },
  "https://fix-price.com/api/sigma/experiment/feature?experiment=chatbot_RAJUTXCv&param=chat_bot": {
    "x-sigma-user-id": [
      "UnY0S1pOK09NY0sraTNyYUlRaFJZdz09OjpBVkRLZlVMcWF1aS8wZEppZVlTUjdBPT0=:877694bb30bad8cdaf6a905f6bb6055e"
    ],
    "x-sigma-platform": [
      "web"
    ],
    "x-sigma-ua": [
      ""
    ],
    "x-sigma-ip": [
      ""
    ],
    "traceparent": [
      "00-a91ec628c02c6fa18efb75e048492dd3-a9a5a350baaac605-00"
    ]
  },
  "https://fix-price.com/img/common/chevron.svg": {
    "traceparent": [
      "00-a91ec628c02c6fa18efb75e048492dd3-a9a5a350baaac605-00"
    ]
  },
  "https://fix-price.com/img/Header/logo.svg": {
    "traceparent": [
      "00-a91ec628c02c6fa18efb75e048492dd3-a9a5a350baaac605-00"
    ]
  },
  "https://fix-price.com/img/common/logout.svg": {
    "traceparent": [
      "00-a91ec628c02c6fa18efb75e048492dd3-a9a5a350baaac605-00"
    ]
  },
  "https://fix-price.com/img/Header/card.svg": {
    "traceparent": [
      "00-a91ec628c02c6fa18efb75e048492dd3-a9a5a350baaac605-00"
    ]
  },
  "https://fix-price.com/img/Header/icons/search.svg": {
    "traceparent": [
      "00-a91ec628c02c6fa18efb75e048492dd3-a9a5a350baaac605-00"
    ]
  },
  "https://fix-price.com/img/common/cart.svg": {
    "traceparent": [
      "00-a91ec628c02c6fa18efb75e048492dd3-a9a5a350baaac605-00"
    ]
  },
  "https://api.fix-price.com/buyer/v1/banner/suitable?type=1&path=https:%2F%2Ffix-price.com%2Fcatalog": {
    "x-language": [
      "ru"
    ],
    "x-city": [
      "3"
    ],
    "x-key": [
      "UnY0S1pOK09NY0sraTNyYUlRaFJZdz09OjpBVkRLZlVMcWF1aS8wZEppZVlTUjdBPT0=:877694bb30bad8cdaf6a905f6bb6055e"
    ],
    "x-logged": [
      ""
    ],
    "x-client-route": [
      "/catalog"
    ]
  },
  "https://api.fix-price.com/buyer/v2/geo/ip": {
    "x-language": [
      "ru"
    ],
    "x-city": [
      "3"
    ],
    "x-key": [
      "UnY0S1pOK09NY0sraTNyYUlRaFJZdz09OjpBVkRLZlVMcWF1aS8wZEppZVlTUjdBPT0=:877694bb30bad8cdaf6a905f6bb6055e"
    ],
    "x-logged": [
      ""
    ],
    "x-client-route": [
      "/catalog"
    ]
  },
  "https://api.fix-price.com/buyer/v1/category/menu": {
    "x-language": [
      "ru"
    ],
    "x-city": [
      "3"
    ],
    "x-key": [
      "UnY0S1pOK09NY0sraTNyYUlRaFJZdz09OjpBVkRLZlVMcWF1aS8wZEppZVlTUjdBPT0=:877694bb30bad8cdaf6a905f6bb6055e"
    ],
    "x-logged": [
      ""
    ],
    "x-client-route": [
      "/catalog"
    ]
  },
  "https://api.fix-price.com/buyer/v1/banner/suitable?type=1&path=https:%2F%2Ffix-price.com%2Fcatalog&utm_referrer=https%3a%2f%2ffix-price.com%2f": {
    "x-language": [
      "ru"
    ],
    "x-city": [
      "3"
    ],
    "x-key": [
      "UnY0S1pOK09NY0sraTNyYUlRaFJZdz09OjpBVkRLZlVMcWF1aS8wZEppZVlTUjdBPT0=:877694bb30bad8cdaf6a905f6bb6055e"
    ],
    "x-logged": [
      ""
    ],
    "x-client-route": [
      "/catalog"
    ]
  },
  "https://api.fix-price.com/buyer/v2/geo/ip?utm_referrer=https%3a%2f%2ffix-price.com%2f": {
    "x-language": [
      "ru"
    ],
    "x-city": [
      "3"
    ],
    "x-key": [
      "UnY0S1pOK09NY0sraTNyYUlRaFJZdz09OjpBVkRLZlVMcWF1aS8wZEppZVlTUjdBPT0=:877694bb30bad8cdaf6a905f6bb6055e"
    ],
    "x-logged": [
      ""
    ],
    "x-client-route": [
      "/catalog"
    ]
  },
  "https://api.fix-price.com/buyer/v1/category/menu?utm_referrer=https%3a%2f%2ffix-price.com%2f": {
    "x-language": [
      "ru"
    ],
    "x-city": [
      "3"
    ],
    "x-key": [
      "UnY0S1pOK09NY0sraTNyYUlRaFJZdz09OjpBVkRLZlVMcWF1aS8wZEppZVlTUjdBPT0=:877694bb30bad8cdaf6a905f6bb6055e"
    ],
    "x-logged": [
      ""
    ],
    "x-client-route": [
      "/catalog"
    ]
  },
  "https://rm.fix-price.com/intake/v2/rum/events": {
    "content-encoding": [
      "gzip"
    ]
  },
  "https://api.fix-price.com/buyer/v1/cookie-config": {
    "x-language": [
      "ru"
    ],
    "x-city": [
      "3"
    ],
    "x-key": [
      "UnY0S1pOK09NY0sraTNyYUlRaFJZdz09OjpBVkRLZlVMcWF1aS8wZEppZVlTUjdBPT0=:877694bb30bad8cdaf6a905f6bb6055e"
    ],
    "x-logged": [
      ""
    ],
    "x-client-route": [
      "/catalog"
    ]
  }
}
