=== Open-Inflation/fixprice_api/tests/__snapshots__/unstandard_headers.schema.json
{
  "type": "object",
  "required": [
    "x-city",
    "x-client-route",
    "x-key",
    "x-language",
    "x-logged"
  ],
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "properties": {
    "content-encoding": {
      "type": "string",
      "enum": [
        "gzip"
      ]
    },
    "traceparent": {
      "type": "string",
      "j2sEnumRejected": true
    },
    "x-city": {
      "type": "string",
      "j2sEnumRejected": true
    },
    "x-client-route": {
      "anyOf": [
        {
          "type": "null"
        },
        {
          "type": "string",
          "enum": [
            "/catalog"
          ]
        }
      ]
    },
    "x-key": {
      "type": "string",
      "j2sEnumRejected": true
    },
    "x-language": {
      "type": "string",
      "enum": [
        "ru"
      ]
    },
    "x-logged": {
      "type": "string",
      "j2sEnumRejected": true
    },
    "x-sigma-ip": {
      "type": "string",
      "j2sEnumRejected": true
    },
    "x-sigma-platform": {
      "type": "string",
      "enum": [
        "web"
      ]
    },
    "x-sigma-ua": {
      "type": "string",
      "j2sEnumRejected": true
    },
    "x-sigma-user-id": {
      "type": "string",
      "j2sEnumRejected": true
    }
  }
}

=== Open-Inflation/fixprice_api/tests/__snapshots__/unstandard_headers.json
{
  "x-language": "ru",
  "x-city": "3",
  "x-key": "UnY0S1pOK09NY0sraTNyYUlRaFJZdz09OjpBVkRLZlVMcWF1aS8wZEppZVlTUjdBPT0=:877694bb30bad8cdaf6a905f6bb6055e",
  "x-logged": "",
  "x-client-route": "/catalog",
  "x-sigma-user-id": "UnY0S1pOK09NY0sraTNyYUlRaFJZdz09OjpBVkRLZlVMcWF1aS8wZEppZVlTUjdBPT0=:877694bb30bad8cdaf6a905f6bb6055e",
  "x-sigma-platform": "web",
  "x-sigma-ua": "",
  "x-sigma-ip": "",
  "traceparent": "00-a91ec628c02c6fa18efb75e048492dd3-a9a5a350baaac605-00",
  "content-encoding": "gzip"
}
